config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations',
                                    registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do

    match 'users/:id', to: 'info#index', as: :info, via: [:get]
    match 'users/:id', to: 'info#update', as: :info_update, via: [:patch]
    post '/autocomplete_city', to: 'autocomplete#autocomplete_city', as: :autocomplete_city


    namespace :admin do
      get '/', to: 'home#index', as: :home
      post '/autocomplete_admin', to: 'autocomplete#autocomplete_admin',
                                  as: :autocomplete_admin

      resources :users, except: %i[new create] do
        get '/password', to: 'users#password', as: :password
        patch '/password', to: 'users#password_change',
                           as: :change_password
        resources :bills, only: %i[show edit update] do
          resources :transactions, only: %i[index show]
        end
      end

      resources :notifications, except: %i[new create destroy] do
        post '/close', to: 'notifications#close', as: :close
        post '/activate_bill', to: 'notifications#activate_bill', as: :activate_bill
      end

      namespace :settings do
        resources :cities
        resources :countries
      end
    end

    namespace :employee do
      get '/', to: 'home#index', as: :home
      resources :bills, only: %i[index show new create] do
        resources :transactions, only: %i[index show]
      end
      resources :replenishment, only: %i[new create]
      resources :transfer, only: %i[new create]
    end
  end

  root to: redirect('/users/sign_in')
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user, foreign_key: :users_id
  has_many :transactions, lambda { |bill|
    unscope(:where)
      .where('sender_id = :id OR recipient_id = :id',
             id: bill.id)
  }
  has_many :sender, class_name: :Transaction, foreign_key: :sender_id
  has_many :recipient, class_name: :Transaction, foreign_key: :recipient_id
  has_many :manager_notifications
  has_one :bill_request

  enum bill_type: { deposit: 1, credit: 2 }

  scope :my_bills, lambda { |users_id|
    joins(:bill_request)
      .where('bills.users_id = ? AND bill_requests.approved_status = ?',
             users_id, BillRequest.approved_statuses[:approved])
  }
  scope :order_by_id, -> { order('id ASC') }

  validates :card_number, length: { is: 16 }
  validates :amount, numericality: true,
                     format: { with: /\A\d{1,6}\.\d{1,2}/,
                               message: I18n.t('validation.amountError') }

  def i_send?(sender_id)
    id == sender_id
  end

  def enough_amount?(send_amount)
    amount < send_amount
  end

  def expired?
    expired_bill_at < Date.today
  end

  def full_info?
    amount_limit.present? && regular_replenishment_amount.present? && percent != 0
  end

end

app/controllers/admin/bills_controller.rb
module Admin
  class BillsController < AdminController
    before_action :set_bill
    before_action :set_user
    before_action :render_breadcrumbs, only: %i[show edit]
    before_action :show_breadcrumbs, only: %i[show edit]

    def show
      @transactions = @bill.transactions.order_by_date
    end

    def edit
      add_breadcrumb I18n.t('breadcrumbs.actions.edit'), :edit_admin_user_bill_path
    end

    def update
      BillsService.new.update_bill(@bill, bill_params)
      UpdateUserBillJob.perform_later(@bill, pundit_user)
      respond_to do |format|
        format.html { redirect_to admin_user_bill_path(@user, @bill), notice: t('bill.messages.successUpdated') }
        format.json { render :show, status: :ok, location: admin_user_bill_path(@user, @bill) }
      end
    rescue ActiveRecord::RecordInvalid => e
      respond_to do |format|
        format.html { redirect_to edit_admin_user_bill_path(@user, @bill), notice: e.message }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end

    private

    def set_user
      @user = @bill.user
    end

    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:expired_bill_at, :percent, :amount_limit,
                                   :regular_replenishment_amount)
    end

    def show_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.bills.bill'), :admin_user_bill_path
    end

    def render_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.users.show', user: @user.full_name_aliases),
                     (proc { admin_user_path(@user.id) })
    end
  end
end

app/controllers/employee/bills_controller.rb
module Employee

  class BillsController < EmployeeController
    before_action :set_user
    before_action :set_bill, only: %i[show destroy]

    add_breadcrumb I18n.t('breadcrumbs.bills.index'), :employee_bills_path

    def index
      @bills = Bill.my_bills @current_user.id
    end

    # GET /bills/1
    # GET /bills/1.json
    def show
      render_breadcrumbs
      @transactions = @bill.transactions.order_by_date.limit(15)
    end

    # GET /bills/new
    def new
      add_breadcrumb I18n.t('breadcrumbs.bills.new'), :new_employee_bill_path
      @bill = Bill.new
    end

    # POST /bills
    # POST /bills.json
    def create
      BillsCreateJob.perform_later(@current_user,
                                   bill_params[:bill_type].to_i, nil,
                                   BillRequest.approved_statuses[:not_approved])

      respond_to do |format|
        format.html { redirect_to employee_bills_path, notice: t('user.message.successOrderingBill') }
        format.json { render :show, status: :created, location: employee_bills_path }
      end
    end

    # DELETE /bills/1
    # DELETE /bills/1.json
    def destroy
      @bill.destroy
      respond_to do |format|
        format.html { redirect_to employee_bills_url, notice: t('user.message.successDestroyBill') }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      params[:id] = params[:bill_id] unless params[:id].present?
      @bill = Bill.find(params[:id])
      my_bill? @bill.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params[:bill][:users_id] = pundit_user.id
      params.require(:bill).permit(:bill_type, :users_id)
    end

    def render_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.bills.show'),
                     (proc { employee_bill_path(@bill.id) })
    end
  end

end

app/helpers/bills_helper.rb
module BillsHelper

  def card_date_expired(date)
    date.strftime('%m/%Y') if date.present?
  end

  def card_number_format(card_number)
    card_number.scan(/.{1,4}/).join(' ')
  end

  def hidden_card_number_format(card_number)
    '●●●● ' + card_number.last(4)
  end

end

app/views/admin/bills/_form.html.erb
<%= form_with(model: bill, url: model_url, local: true,
              html: { autocomplete: 'off' }) do |form| %>

  <div class="form-group">
    <%= form.label :expired_bill_at, t('bill.field.date_expired') %>
    <%= datepicker(form, :expired_bill_at, bill) %>
    <% if bill.errors[:expired_bill_at].any? %>
      <span class="invalid-feedback">
        <strong><%= bill.errors.messages[:expired_bill_at][0] %></strong>
      </span>
    <% end %>
  </div>

  <% if bill.credit? %>
    <%= render(partial: 'partials/bills/credit_edit_admin', locals: { form: form }) %>
  <% end %>

  <div class="actions">
    <%= form.submit button_name, class: 'btn btn-success mb-3' %>
  </div>
<% end %>

app/views/admin/bills/edit.html.erb
<div class="card shadow">
  <div class="card-header">
    <%= t('user.action.edit') %>
  </div>
  <div class="card-body">
    <%= render 'form', bill: @bill, model_url: admin_user_bill_path(@user), button_name: t('action.edit') %>
  </div>
</div>

app/views/admin/bills/show.html.erb
<div class="buttons row">
  <%= link_to t('bill.actions.edit_bill'), edit_admin_user_bill_path(@user, @bill), class: 'btn btn-primary mb-3 mr-2' %>
</div>
<div class="row">
  <div class="col-md-5 mb-3">
    <%= render(partial: 'partials/bills/bill_info', locals: { bill: @bill }) %>
  </div>
  <div class="col-md-7">
    <div class="card shadow">
      <div class="card-header">
        <strong><%= t('bill.field.card_new_transaction') %></strong>
        <%= link_to t('bill.all_transactions'), admin_user_bill_transactions_path(@user, @bill), class: 'btn btn-sm btn-outline-secondary float-right' %>
      </div>
      <%= render(partial: 'partials/transactions/list', locals: { transactions: @transactions,
                                                                  user: pundit_user }) %>
    </div>
  </div>
</div>