config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations',
                                    registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do

    match 'users/:id', to: 'info#index', as: :info, via: [:get]
    match 'users/:id', to: 'info#update', as: :info_update, via: [:patch]
    post '/autocomplete_city', to: 'autocomplete#autocomplete_city', as: :autocomplete_city


    namespace :admin do
      get '/', to: 'home#index', as: :home
      post '/autocomplete_admin', to: 'autocomplete#autocomplete_admin',
                                  as: :autocomplete_admin

      resources :users, except: %i[new create] do
        get '/password', to: 'users#password', as: :password
        patch '/password', to: 'users#password_change',
                           as: :change_password
        resources :bills, only: %i[show edit update] do
          resources :transactions, only: %i[index show]
        end
      end

      resources :notifications, except: %i[new create destroy] do
        post '/close', to: 'notifications#close', as: :close
        post '/activate_bill', to: 'notifications#activate_bill', as: :activate_bill
      end

      namespace :settings do
        resources :cities
        resources :countries
      end
    end

    namespace :employee do
      get '/', to: 'home#index', as: :home
      resources :bills, only: %i[index show new create] do
        resources :transactions, only: %i[index show]
      end
      resources :replenishment, only: %i[new create]
      resources :transfer, only: %i[new create]
    end
  end

  root to: redirect('/users/sign_in')
end

app/models/user.rb
# frozen_string_literal: true

# @class User
# @extend ApplicationRecord
# User model
# @param integer id
# @param string email
# @param string first_name
# @param string last_name
# @param string second_name
# @param string status
# @param integer phone
# @param date birthday
# @param integer gender
class User < ApplicationRecord

  belongs_to :city, optional: true, foreign_key: :cities_id
  has_many :bills, -> { order_by_id }, foreign_key: :users_id
  has_many :manager_notifications, foreign_key: :admin_id
  has_many :bill_requests, foreign_key: :admin_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  DENY_DOMAINS = %w[test.com test.ru test.ua admin.com admin.ua admin.ru].freeze
  DENY_NAMES = %w[test administrator].freeze

  enum role: { admin: 1, user: 2 }, _suffix: true
  enum status: %i[active disable deleted blocked]
  enum gender: { male: 1, female: 2 }

  scope :admins, -> { where(role: :admin) }
  scope :employees, -> { where(role: :user) }

  validates_each :first_name, :last_name, :second_name do |record, attr, value|
    if value =~ /\A[а-яёїіє|a-z]/
      record.errors.add(attr, 'must start with upper case')
    end
  end
  validates :phone, numericality: { only_integer: true },
                    length: { is: 9 },
                    allow_blank: true
  validates :password, confirmation: true
  validate :email_start_is_deny?
  validate :email_end_is_deny?

  def full_name?
    first_name.nil? && last_name.nil?
  end

  def full_name
    "#{last_name.present? ? last_name : ''} #{first_name.present? ? first_name : ''} #{second_name.present? ? second_name : ''}"
  end

  def full_name_aliases
    "#{last_name.present? ? last_name : ''} #{first_name.present? ? first_name.chr + '.' : ''} #{second_name.present? ? second_name.chr + '.' : ''}"
  end

  def gender_name
    return I18n.t('user.gender.male') if male?
    I18n.t('user.gender.female') if female?
  end

  private

  def email_end_is_deny?
    DENY_DOMAINS.each do |domain|
      errors.add(:email, I18n.t('messages.errorDomain')) if email.end_with?('@' + domain)
    end
  end

  def email_start_is_deny?
    DENY_NAMES.each do |name|
      errors.add(:email, I18n.t('messages.errorName')) if email.start_with?(name + '@')
    end
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :set_user, only:
        %i[show edit update destroy password password_change]
    add_breadcrumb I18n.t('breadcrumbs.users.index'),
                   :admin_users_path

    # GET /users
    # GET /users.json
    def index
      @users = User.order(:id).page(params[:page])
    end

    # GET /users/1
    # GET /users/1.json
    def show
      render_breadcrumbs
    end

    # GET /users/new
    #def new
    #  @user = User.new
    #end

    # GET /users/1/edit
    def edit
      render_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.users.edit'),
                     :edit_admin_user_path
    end

    # POST /users
    # POST /users.json
    #def create
    #  @user = User.new(user_params)
    #
    #  respond_to do |format|
    #    if @user.save
    #      format.html do
    #        redirect_to admin_settings_user_path(@user),
    #                    notice: t('user.message.successCreate')
    #      end
    #      format.json do
    #        render :show, status: :created,
    #                      location: admin_settings_user_path(@user)
    #      end
    #    else
    #      format.html { render :new }
    #      format.json { render json: @user.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html do
            redirect_to admin_user_path(@user),
                        notice: t('user.message.successUpdate')
          end
          format.json do
            render :show, status: :ok,
                   location: admin_user_path(@user)
          end
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html do
          redirect_to admin_users_url,
                      notice: t('user.message.successDestroy')
        end
        format.json { head :no_content }
      end
    end

    # GET /users/1/password
    def password
      render_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.users.password'),
                     :admin_user_password_path
    end

    # POST /users/1/password
    def password_change
      if @user.update(password_params)
        if InfoService.new.check_users(@user.id, session[:user_id])
          flash[:warning] = I18n.t('messages.enter_password')
          session.clear
          redirect_to root_path
        else
          flash[:success] = I18n.t('messages.password_updated')
          redirect_to admin_user_path(@user)
        end
      else
        render :update
      end
    end

    private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :second_name,
                                   :birthday, :gender, :role, :cities_id,
                                   :phone)
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def render_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.users.show', user: @user.full_name_aliases),
                     (proc { admin_user_path(@user.id) })
    end
  end
end

app/views/admin/users/partials/_bills.html.erb
<div class="card card-width shadow rounded
      <% if bill.bill_request.present? %>
        <%= bill.bill_request.approved? ? 'border border-success' : 'border border-danger' %>
      <% else %>
        border border-danger
      <% end %>
      <%= bill.credit? ? 'credit' : 'deposit' %>-card m-2">
  <div class="card__face card--front">
    <div>
      <a class="text-white cursor-auto" href="<%= admin_user_bill_path(@user, bill) %>">
        <i class="fa fa-sm fa-sign-in open-card float-left ml-3 mt-2"></i>
      </a>
      <i class="fa fa-sm fa-copy copy-icon float-right mr-3 mt-2 cursor-auto"></i>
    </div>
    <img src="/images/card_logo.svg" width="25" height="25" class="align-top card-image" alt="">
    <div class="card-body text-center">
      <span class="card-number"><%= card_number_format(bill.card_number) %></span> <br>
      <span class="card-date"><%= card_date_expired(bill.expired_bill_at) %></span>
    </div>
  </div>
  <div class="card__face card--back">
    <div class="card-body pt-2">
      <p class="mb-0 mt-0"><%= t('bill.field.amount') %>:
        <span class="amount"><%= number_to_currency bill.amount %></span>
      </p>
      <% if bill.credit? %>
        <p class="mb-0 mt-0"><%= t('bill.field.percent') %>:
          <span class=""><%= bill.percent %> %</span>
        </p>
        <p class="mb-0 mt-0"><%= t('bill.field.replenishment_at') %>:
          <span class=""><%= bill.replenishment_at %></span>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/partials/_form.html.erb
<%= form_with(model: user, url: model_url, html: { autocomplete: 'off' },
              local: true) do |form| %>

  <div class="form-group">
    <%= form.label :first_name, t('user.field.first_name') %>
    <%= form.text_field :first_name, class: "form-control #{' is-invalid ' if user.errors[:first_name].any? }",
                        placeholder: 'Enter first name', required: 'true' %>
    <% if user.errors[:first_name].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:first_name][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, t('user.field.last_name') %>
    <%= form.text_field :last_name, class: "form-control #{' is-invalid ' if user.errors[:last_name].any? }",
                        placeholder: 'Enter last name', required: 'true' %>
    <% if user.errors[:last_name].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:last_name][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :second_name, t('user.field.second_name') %>
    <%= form.text_field :second_name, class: "form-control #{' is-invalid ' if user.errors[:second_name].any? }",
                        placeholder: 'Enter second name' %>
    <% if user.errors[:second_name].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:second_name][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :birthday, t('user.field.birthday') %>
    <%= datepicker(form, :birthday, user) %>
    <% if user.errors[:birthday].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:birthday][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= label :gender, t('user.field.gender') %>
    <div class="row d-flex justify-content-around">
      <div class="form-check form-check-inline">
        <%= form.radio_button :gender, User.genders.key(User.genders[:male]), class: 'form-check-input' %>
        <%= form.label :gender, t('user.gender.male'), value: User.genders.key(User.genders[:male]), class: 'form-check-label' %>
      </div>
      <div class="form-check form-check-inline">
        <%= form.radio_button :gender, User.genders.key(User.genders[:female]), class: 'form-check-input' %>
        <%= form.label :gender, t('user.gender.female'), value: User.genders.key(User.genders[:female]), class: 'form-check-label' %>
      </div>
    </div>
    <% if user.errors[:gender].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:gender][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= label :role, t('user.field.role') %>
    <div class="row d-flex justify-content-around">
      <div class="form-check form-check-inline">
        <%= form.radio_button :role, User.roles.key(User.roles[:admin]), class: 'form-check-input' %>
        <%= form.label :role, t('user.role.admin'), value: User.roles.key(User.roles[:admin]), class: 'form-check-label' %>
      </div>
      <div class="form-check form-check-inline">
        <%= form.radio_button :role, User.roles.key(User.roles[:user]), class: 'form-check-input' %>
        <%= form.label :role, t('user.role.employee'), value: User.roles.key(User.roles[:user]), class: 'form-check-label' %>
      </div>
    </div>
    <% if user.errors[:role].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:role][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :city, t('user.field.city') %>
    <%= form.hidden_field :cities_id %>
    <%= form.text_field :city, class: "form-control #{' is-invalid ' if user.errors[:city].any? }",
                        value: user.city.present? ? user.city.name : ''%>
    <% if user.errors[:city].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:city][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="form-group phone-group__div <%= user.city.present? ? '' : 'd-none' %>">
    <%= form.label :phone, t('user.field.phone') %>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-phone_number">+<%= user.city.present? ? user.city.country.phone_code : '' %></span>
      </div>
      <%= form.number_field :phone, class: "form-control #{' is-invalid ' if user.errors[:phone].any? }",
                            placeholder: '000000000' %>
    </div>
    <% if user.errors[:phone].any? %>
      <span class="invalid-feedback">
        <strong><%= user.errors.messages[:phone][0] %></strong>
      </span>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit button_name, class: 'btn btn-success mb-3' %>
  </div>
<% end %>