config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations',
                                    registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do

    match 'users/:id', to: 'info#index', as: :info, via: [:get]
    match 'users/:id', to: 'info#update', as: :info_update, via: [:patch]
    post '/autocomplete_city', to: 'autocomplete#autocomplete_city', as: :autocomplete_city


    namespace :admin do
      get '/', to: 'home#index', as: :home
      post '/autocomplete_admin', to: 'autocomplete#autocomplete_admin',
                                  as: :autocomplete_admin

      resources :users, except: %i[new create] do
        get '/password', to: 'users#password', as: :password
        patch '/password', to: 'users#password_change',
                           as: :change_password
        resources :bills, only: %i[show edit update] do
          resources :transactions, only: %i[index show]
        end
      end

      resources :notifications, except: %i[new create destroy] do
        post '/close', to: 'notifications#close', as: :close
        post '/activate_bill', to: 'notifications#activate_bill', as: :activate_bill
      end

      namespace :settings do
        resources :cities
        resources :countries
      end
    end

    namespace :employee do
      get '/', to: 'home#index', as: :home
      resources :bills, only: %i[index show new create] do
        resources :transactions, only: %i[index show]
      end
      resources :replenishment, only: %i[new create]
      resources :transfer, only: %i[new create]
    end
  end

  root to: redirect('/users/sign_in')
end

app/views/layouts/navigation/_admin.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark bg-light rounded-bottom mb-4 shadow">
  <a class="navbar-brand" href="<%= admin_home_path %>">
    <img src="/images/moon_logo.svg" width="25" height="25" class="d-inline-block align-top" alt="">
    <%= t('appName') %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link <%= current_page?(admin_notifications_path) ? ' active ' : '' %>"
           href="<%= admin_notifications_path %>">
          <%= t('notifications.field.header') %>
          <sup><i class="badge badge-danger align-top"><%= @count_notifications %></i></sup>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <%= current_page?(admin_users_path) ? ' active ' : '' %>"
           href="<%= admin_users_path %>">
          <%= t('user.field.users') %>
        </a>
      </li>
      <%= render('layouts/navigation/user_info') %>
    </ul>
  </div>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= pundit_user.full_name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to admin_settings_countries_path, method: :get, class: 'dropdown-item' do %>
              <i class="fa fa-cog"></i> <%= t('action.settings') %>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
              <i class="fa fa-sign-out"></i> <%= t('action.logOut') %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<%= render('layouts/navigation/breadcrumbs') %>

app/views/layouts/navigation/_breadcrumbs.html.erb
<nav aria-label="breadcrumb">
  <ol class='breadcrumb shadow'>
    <%= render_breadcrumbs tag: :li, separator: ' / ' %>
  </ol>
</nav>

app/views/layouts/navigation/_employee.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark bg-light rounded-bottom mb-4 shadow">
  <a class="navbar-brand" href="<%= employee_home_path %>">
    <img src="/images/moon_logo.svg" width="25" height="25" class="d-inline-block align-top" alt="">
    <%= t('appName') %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <%= render('layouts/navigation/user_info') %>
      <li class="nav-item">
        <a class="nav-link <%= current_page?(employee_bills_path) ? ' active ' : '' %>"
           href="<%= employee_bills_path %>">
          <%= t('user.field.bills') %>
        </a>
      </li>
    </ul>
  </div>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= pundit_user.full_name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
              <i class="fa fa-sign-out"></i> <%= t('action.logOut') %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<%= render('layouts/navigation/breadcrumbs') %>

app/views/layouts/navigation/_footer.html.erb
<footer class="mt-4 container text-center">
  <div class="social">
    <a class="cursor-unset text-body" href="https://www.instagram.com/sanya._.s/"><i class="fa fa-2x fa-instagram"></i></a>
  </div>
  <div class="rights">
    <p class="noselect">© <%= DateTime.now.year %>. All rights Reserved.
      <br>
      Site by Sanya Syvolap
    </p>
  </div>
</footer>

app/views/layouts/navigation/_user_info.html.erb
<li class="nav-item">
  <a class="nav-link <%= current_page?(info_path(pundit_user)) ? ' active ' : '' %>"
     href="<%= info_path(pundit_user) %>">
    <%= t('user.field.myInfo') %>
    <% if pundit_user.full_name? %>
      <span class="badge badge-danger"><%= t('action.warning') %>!</span>
    <% end %>
  </a>
</li>